spring:
  application:
    name: anti-fraud-app
  profiles:
    active: local
  kafka:
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "com.bank.antifraud.DTO, com.bank.antifraud.Entities"
        spring.json.value.default.type: com.bank.antifraud.Entities.TransferChecked
